Update link checker

diff --git a/.github/workflows/md-link-check.yaml b/.github/workflows/md-link-check.yaml
--- a/.github/workflows/md-link-check.yaml
+++ b/.github/workflows/md-link-check.yaml
@@ -10,23 +10,27 @@ jobs:
     # checkout to latest commit
     - uses: actions/checkout@master
     # run markdown linter
-    - uses: BoundfoxStudios/action-hugo-link-check@v2
-      id: link-check
-      continue-on-error: true
-      with:
-        timeout: 300
-        fail-on-broken-links: 0
-        hugo-startup-wait-time: 120
-        hugo-root: ./
-        hugo-content-dir: ./content
-        hugo-config: ./config.yaml
-    - name: "Print Broken Links"
-      run: |
-        BROKEN_LINK_COUNT="${{ steps.link-check.outputs.broken-links-count }}"
-        if [[ "$BROKEN_LINK_COUNT" -gt 0 ]]; then
-          echo ${{ steps.link-check.outputs.broken-links}}
-          exit 1
-        else
-          echo "No broken link found"
-          exit 0
-        fi
+    - name: Check for broken Links
+      uses: marojor/hugo-broken-link-checker@v1.0.5
+      # with:
+      #   skip-file: 'skip-rules-for-broken-links-check.txt'
+    # - uses: BoundfoxStudios/action-hugo-link-check@v2
+    #   id: link-check
+    #   continue-on-error: true
+    #   with:
+    #     timeout: 300
+    #     fail-on-broken-links: 0
+    #     hugo-startup-wait-time: 120
+    #     hugo-root: ./
+    #     hugo-content-dir: ./content
+    #     hugo-config: ./config.yaml
+    # - name: "Print Broken Links"
+    #   run: |
+    #     BROKEN_LINK_COUNT="${{ steps.link-check.outputs.broken-links-count }}"
+    #     if [[ "$BROKEN_LINK_COUNT" -gt 0 ]]; then
+    #       echo ${{ steps.link-check.outputs.broken-links}}
+    #       exit 1
+    #     else
+    #       echo "No broken link found"
+    #       exit 0
+    #     fi
